site_name: 69503891's Notebook
copyright: "&copy; 2024 Masayuki Higashino"
site_url: https://mh61503891.github.io/notebook/
repo_url: https://github.com/mh61503891/notebook
site_description: 質問された事などをまとめています。
repo_name: mh61503891/notebook
edit_uri: edit/main/docs/
plugins:
  - enumerate-headings:
      toc_depth: 0
      strict: true
      increment_across_pages: false
      exclude:
        - "*"
  # - git-committers:
  #     repository: mh61503891/notebook
  #     branch: main
  - git-revision-date-localized:
      enable_creation_date: true
      type: custom
      custom_format: "%Y-%m-%d %H:%M"
  - rss
  - search
  - social:
      cards_layout_options:
        font_family: Noto Sans JP
  - tags:
      tags_file: tags.md
theme:
  name: material
  logo: assets/mh61503891-512x512.png
  favicon: assets/mh61503891-512x512.png
  icon:
    repo: fontawesome/brands/github-alt
  font:
      code: JetBrains Mono
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.top
  custom_dir: overrides
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mh61503891
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/61503891
  generator: false
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:pymdownx.superfences.fence_code_format"
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      use_pygments: true
      # noclasses: false
      pygments_lang_class: true
      # linenums: true
  - tables
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Tips:
    - tips/index.md
  - Unix:
    - unix/index.md
    - Commands:
      - unix/commands/aria2.md
      - unix/commands/echo.md
      - unix/commands/grep.md
      - unix/commands/tail.md
  - Windows:
    - windows/index.md
  - Tags: tags.md
  - Search: search.md
