site_name: Tips
copyright: "&copy; 2024 Masayuki Higashino"
site_url: https://mh61503891.github.io/tips/
repo_url: https://github.com/mh61503891/tips
repo_name: mh61503891/tips
plugins:
  - search
  - git-revision-date
  - tags:
      tags_file: tags.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  font:
      text: Noto Sans JP
      code: Inconsolata
  language: ja
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - Tips:
    - tips/index.md
  - Unix:
    - unix/index.md
    - Commands:
      - unix/commands/aria2.md
      - unix/commands/echo.md
      - unix/commands/grep.md
      - unix/commands/tail.md
  - Windows:
    - windows/index.md
  - Tags: tags.md