site_name: 69503891's Notebook
copyright: "&copy; 2024 Masayuki Higashino"
site_url: https://mh61503891.github.io/notebook/
repo_url: https://github.com/mh61503891/notebook
repo_name: mh61503891/notebook
# view_uri: blob/main/docs/
edit_uri: edit/main/docs/
plugins:
  - rss
  - search
  - git-revision-date
  - tags:
      tags_file: tags.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  font:
      text: Noto Sans JP
      code: Inconsolata
  language: ja
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - content.action.edit
    # - content.action.view
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.top
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Tips:
    - tips/index.md
  - Unix:
    - unix/index.md
    - Commands:
      - unix/commands/aria2.md
      - unix/commands/echo.md
      - unix/commands/grep.md
      - unix/commands/tail.md
  - Windows:
    - windows/index.md
  - Tags: tags.md
